export const LABEL_LIST: object = {
  address: 'Address',
  agent: 'Agent',
  capacity: 'Capacity',
  chamber: 'Chamber',
  chamberId: 'Chamber',
  customer: 'Party',
  date: 'Date',
  father: 'Father',
  floor: 'Floor',
  floorId: 'Floor',
  inventoryType: 'Type',
  lineId: 'Line',
  name: 'Name',
  phone: 'Phone',
  quantity: 'Quantity',
  sr_no: 'SR #',
  userName: 'Username',
  userEmail: 'Email',
  userLastName: 'Last Name',
  vouchar_no: 'Vouchar#',
  year: 'Year',
};
