export const LABEL_LIST: object = {
  address: 'Address',
  agent: 'Agent',
  capacity: 'Capacity',
  chamber: 'Chamber',
  chamberId: 'Chamber',
  customer: 'Party',
  date: 'তারিখ',
  father: 'Father',
  floor: 'Floor',
  floorId: 'Floor',
  inventoryType: 'Type',
  lineId: 'Line',
  loan_amount: 'Amount',
  loan_rate: 'Rate',
  loan_profit: 'Profit',
  loan_payable: 'Payable',
  name: 'Name',
  phone: 'Phone',
  quantity: 'মোট বস্তার সংখ্যা',
  sr_no: 'লট নং',
  userName: 'Username',
  userEmail: 'Email',
  userLastName: 'Last Name',
  vouchar_no: 'ক্রমিক নং ',
  year: 'বছর',
};
